### ISSUE TITLE
cc-ctl fails with 400 when variables are not exported

### ISSUE THREAD

**Issue by salaboy** [salaboy/camunda-cloud-go-client#19] opened 2021-03-12 15:50 UTC
We need to improve the error message for when the CC_CLIENT_ID and CC_CLIENT_SECRET are not exported.. currently it is showing: 

```
salaboy> cc-ctl 
2021/03/12 15:46:36 HTTP Error trying to login, 400
```

Instead, we should get something like this: 
```
Camunda Cloud CLI to interact with Camunda Cloud Resources.
  You can create a Camunda Cloud Account here: https://accounts.cloud.camunda.io/signup
  Then you need to go to <YOUR USER>(Top right corner) -> Organization Settings -> Cloud Management API 
  and Create a new client. You need to copy and save the Client Id and the Secret Id from that client. 
  You need to export the following variables for this command to interact with a Camunda Cloud Account:
  - export CC_CLIENT_ID=<YOUR CLIENT ID>
  - export CC_CLIENT_SECRET=<YOUR CLIENT SECRET>
```

and when I export the variables I get: 

```
salaboy> cc-ctl                                                  
Camunda Cloud CLI to interact with Camunda Cloud Resources.
  You can create a Camunda Cloud Account here: https://accounts.cloud.camunda.io/signup
  Then you need to go to <YOUR USER>(Top right corner) -> Organization Settings -> Cloud Management API 
  and Create a new client. You need to copy and save the Client Id and the Secret Id from that client. 
  You need to export the following variables for this command to interact with a Camunda Cloud Account:
  - export CC_CLIENT_ID=<YOUR CLIENT ID>
  - export CC_CLIENT_SECRET=<YOUR CLIENT SECRET>
  
  Available Commands:  
  # List all clusters
  cc-ctl clusters get --all

  # Get cluster from id
  cc-ctl clusters get --id <cluster_id>

  # Get cluster from name
  cc-ctl clusters get --name <cluster_name>

  # Delete cluster from id
  cc-ctl clusters delete --id <cluster_id>

  # Delete cluster from name
  cc-ctl clusters delete --name <cluster_name>

  # Create cluster from default configuration
  cc-ctl clusters create --default --name <cluster_name>

Usage:
  cc-ctl [command]

Available Commands:
  clusters    Manage your cluster's resources on Camunda Cloud
  help        Help about any command

Flags:
  -h, --help   help for cc-ctl

Use "cc-ctl [command] --help" for more information about a command.
```

**Comment by tusharmitroo** [comment] 2021-04-04 11:51
Hello salaboy,

I have been learning go and also looking into this project and found this good first issue. I build it on my machine using make build command and could reproduce the same error by running the cc-ctl binary from the bin directory.

I started looking into the code and found that we read the CC_CLIENT_ID and CC_CLIENT_SECRET environment variables in main.go. Since os.Getenv returns an empty string, the code proceeds further with the execution and prints a 400 response. 

I can fix this issue by checking if these environment variables are not empty ("") before calling the client.Login(ClientId, ClientSecret) method.

It would be great if you could assign this issue to me as my first ever contribution.

Thanks,
Tushar

**Comment by salaboy** [comment] 2021-04-04 17:56
@tusharmitroo yeah that sounds cool, but as part of the PR it will be great if we can add a test to make sure that we don't break this in the future. I will assign this issue to you.

**Comment by tusharmitroo** [comment] 2021-04-04 18:09
@salaboy Thanks for assigning the issue. Nice thought, I will add a test case for this.

**Comment by salaboy** [comment] 2021-04-05 08:57
@tusharmitroo please pull all the new changes, as I did a bit of a refactoring

**Comment by tusharmitroo** [comment] 2021-04-06 12:14
@salaboy yeah will do so.

**Comment by salaboy** [comment] 2021-04-15 09:22
@tusharmitroo any news?

**Comment by tusharmitroo** [comment] 2021-04-15 15:56
Hi @salaboy , sorry for the delay. I have raised a PR with a check for the environment variables before calling the login function and a test case for the same.

**Comment by tusharmitroo** [comment] 2021-04-23 14:45
Here is the link of the pull request for reference: #20

**Closed as completed** 2021-10-03 23:16 UTC
Labels: good first issue
